apiVersion: v1
kind: Service
metadata:
  name: demo-deploy-service
  namespace: default
spec:
  selector:
    app: demo-deploy
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
  type: NodePort
  